language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: A8H0nAY80/TxbaDYGvGUlqNKv6ddv9Gy4qgynMPnmVf42lbX+sDO7bFEH541WA1Kzuqbm4Uw91ju8aW8MHFsxhtj/RvYpUa2CGhjVf3FdaSMpsKp/NytynyV79FAGYM1aoFS1ZtwcD0aqOGKkZHLNSOhF5G6X5U7ijz2muXTKK3iqCnXbPSv5Gxxp1igbcgDrdrRISD6VQN64bxagw8geTiwujvQ+O24+FyJr/TnYy5FF8sN/qEsLYswq8HRvJE+AENCscW0B2H8uRhP4Utz0EckX6nnO2h9GETQZf7gWgpVdlzm/OPgH8N6kY9bSfiibxdSqeFgBq1+7QZ4Jq5dSkpkIuvkHc9A0TqMziewjYntONI8a6g2wuFzImXJ3Dket6uhhw9lz4tC5KTUVU91EIvzdLuaEHZlrRyReTVJL9a59JIi9DW/jYfG075pz6iXcbaavuXBktvf+7Qw41DZZUsJ61bj5jlHtmMlI1ByTdhL1oPfWprlrVUHgky+2ncwcf7EUsqOgPDGkakr5UTRPwQeMA5URR8DBRApMQ5CS7k5+vf9mAF2tB7Q+Cwb5fxpE3S5RSOMPTskIXblpzgdk0QW1+YoSgIapRZwryJMVH2phaWO+iCNnxPQwQiHWDQePJ/AfZMQomvyRXxn4rWwXmJaoS8slWfYa2n0/cBR31o=
  app: stormy-badlands-44481
  on:
    repo: afterburnerDS/reactCapiApi
