language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: WSvE3PMaag2FWWQr0P3PItSGh7WkSQvbQeHoI2ItBxRHaZqm2SNS7M3+Vfw6iUni/fFBocaCOJjta+OC3vmIIIq0dDH/SS7Gb6iiidRbBB3wsSlJoUNDHbmWqc8CTSAveY1/KrhyRdSod30HuL8VPlM+GW5SfInJjab8aoVMaj9WFVh/sAfUMlJ6CwQlhEYI5UxO3UBWe3NaRFUR9jPvhCjB3NphnOWC9ywQekPEGsaX7t6ExVY6N6scD7eE+XK85CCDeQoqOc1j+3thnAwV8pWtoy+SFZEWhceT+IYMi4UQKqtG8vIlqI+zTGM95JEbIaiXBWvcN55ZmO1p0gCQJU48ZaGXNgSunBe7VBsNt5ThQCPFoDeuiM36dk5LcssgnHgqNavjZuYNVQm29heAWLFl9uQ1w6e9QiNQgG9LZqxmcoaJL5jqNELxSgLQuaR0iIlXSw3aQrsCZ33Ys7PS47Cc524k7JOPCvOkhHoY0iW2uyXgiMtCAAvw4ErhIRg1BK5fFqy1x9a9oB1PFbODjdoobLGhfSuLcj8YVKnZ++LQNXKCMEacAfa5tPbYk1L+eBBG0C30ggd4+8WwV7hqrc1GJLbpSXKE6/ny78KCaDPQOyCdAzv3kmcOVf6OB0rpq5Twxq/JULMQ167N6AH4DF1rMpExsb1ittaCSONWMyo=
  app: safe-plateau-75730
  on:
    repo: afterburnerDS/reactCapiApi
